# Generated by Django 3.1.2 on 2020-10-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoot',
            name='total_like',
            field=models.IntegerField(default=0),
        ),
    ]
