# Generated by Django 3.1.2 on 2020-10-28 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_hoot_total_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoot',
            old_name='total_like',
            new_name='total_likes',
        ),
    ]
