# Generated by Django 3.1.2 on 2020-10-29 04:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201028_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoot',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 10, 29, 4, 11, 31, 153972, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
